openapi: 3.0.0
info:
  version: 1.0.0
  title: shopping
  description: shopping cart api
  
servers:
  - url: http://localhost:9080/api
    description: locally hosted api

components:
  schemas:
  
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetail'
          
    
    ErrorDetail:
      type: object
      required:
        - message
      properties:
        code:
          type: string
        message:
          type: string
          
    CartItem:
      type: object
      required:
      - sku
      - quantity
      properties:
        sku:
          type: string
        quantity:
          type: integer
          
          
    Promotion:
      type: object
      required:
        - buy
        - type
        - info
      properties:
        buy:
          type: integer
        type: 
          type: string
        info:
          type: string
        units:
          type: integer
        rate:
          type: number
          format: float
          multipleOf: 0.01
        item:
          type: string
          
    Cart:
      type: object
      required:
        - id
        - state
      properties:
        id:
          type: string
        state:
          $ref: '#/components/schemas/CartState'
          
    CartState:
      type: object
      required:
        - baseAmount
        - cartAmount
        - lineItems
      properties:
        baseAmount:
          type: number
          format: float
          multipleOf: 0.01
        cartAmount:
          type: number
          format: float
          multipleOf: 0.01
        lineItems:
          type: array
          items:
            $ref: '#/components/schemas/EvaluatedItem'
    
    EvaluatedItem:
      type: object
      required:
      - sku
      - quantity
      - listPrice
      - salePrice
      - discount
      - promotions
      properties:
        sku:
          type: string
        quantity:
          type: integer
        listPrice:
          type: number
          format: float
          multipleOf: 0.01
        salePrice:
          type: number
          format: float
          multipleOf: 0.01
        discount:
          type: number
          format: float
          multipleOf: 0.01
        promotions:
          type: array
          items:
            $ref: '#/components/schemas/Promotion'
          
  requestBodies:
    NewCartRq:
      content:
        application/json:
          examples:
            googlehomes:
              summary: buy three google homes at price of two
              value:
                lineItems:
                  - sku: 120P90
                    quantity: 3
            macbookpro:
              summary: free raspberry pi with macbook pro
              value:
                lineItems:
                  - sku: 43N23P
                    quantity: 1
                  - sku: "234234"
                    quantity: 1
            alexa:
              summary: buy three or more alexa speakers and have 10 percent discount on all
              value:
                lineItems:
                  - sku: A304SD
                    quantity: 3
          schema:
            required:
              - lineItems
            properties:
              lineItems:
                type: array
                items:
                  $ref: '#/components/schemas/CartItem'
  
  
  responses:
    ErrorRs:
      description: standard error response
      content:
        application/json:
          example:
            code: 3
            message: cart item(s) stock is less than requested quantity
            details:
              - message: item (Alexa Speaker) current availablity 10
          schema:
            $ref: '#/components/schemas/Error'
    CartRs:
      description: server side evaluated standard cart response
      content:
        application/json:
          examples:
            googlehomes:
              summary: buy three google homes at price of two
              value:
                id: e73e0312-19fb-4c63-96ab-c208f7569bc9
                state:
                  baseAmount: 149.97
                  cartAmount: 99.98
                  lineItems:
                  - discount: 49.99
                    listPrice: 49.99
                    promotions:
                    - buy: 3
                      info: buy 3 of (Google Home) for a price of 2
                      type: PRICE
                      units: 2
                    quantity: 3
                    salePrice: 99.98
                    sku: 120P90
            macbookpro:
              summary: free raspberry pi with macbook pro
              value:
                id: 91bf9970-89d2-45b9-9c51-f3a05df4d6d8
                state:
                  baseAmount: 5459.99
                  cartAmount: 5429.99
                  lineItems:
                  - discount: 0
                    listPrice: 5399.99
                    promotions:
                    - buy: 1
                      info: free 1 (Raspberry Pi B) with 1 of (MacBook Pro)
                      item: '234234'
                      type: FREE
                      units: 1
                    quantity: 1
                    salePrice: 5399.99
                    sku: 43N23P
                  - discount: 30
                    listPrice: 30
                    promotions: []
                    quantity: 2
                    salePrice: 30
                    sku: '234234'
                    
            alexa:
              summary: buy three or more alexa speakers and have 10 percent discount on all
              value:
                id: d1b12def-fc77-460c-979a-4f9c6cd646c2
                state:
                  baseAmount: 328.5
                  cartAmount: 295.65
                  lineItems:
                  - discount: 32.85
                    listPrice: 109.5
                    promotions:
                    - buy: 3
                      info: buy 3 or more (Alexa Speaker) and have 10.00 percent discount on all
                      rate: 10
                      type: DISCOUNT
                    quantity: 3
                    salePrice: 295.65
                    sku: A304SD
                
          schema:
            $ref: '#/components/schemas/Cart'
  
paths:
  /cart:
    post:
      operationId: newCart
      description: create a cart with given list of items
      requestBody:
        $ref: '#/components/requestBodies/NewCartRq'
      responses:
        200:
          $ref: '#/components/responses/CartRs'
        default:
          $ref: '#/components/responses/ErrorRs'
          
  /cart/{id}:
    get:
      operationId: getCart
      description: for a given cart identifier return the state
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/CartRs'
        default:
          $ref: '#/components/responses/ErrorRs'